# Generated by Django 3.0.7 on 2022-06-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybakery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
