# Generated by Django 3.0.7 on 2022-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
